/* Automatically generated by './build/bin/build-entry.js' */

import Pagination from '../package/pagination/index.js';
import Dialog from '../package/modal/index.js';
import Alert from '../package/alert/index.js';
import Autocomplete from '../package/autocomplete/index.js';
import Dropdown from '../package/dropdown/index.js';
import DropdownMenu from '../package/dropdown-menu/index.js';
import DropdownItem from '../package/dropdown-item/index.js';
import Menu from '../package/menu/index.js';
import Submenu from '../package/submenu/index.js';
import MenuItem from '../package/menu-item/index.js';
import MenuItemGroup from '../package/menu-item-group/index.js';
import Input from '../package/input/index.js';
import InputNumber from '../package/input-number/index.js';
import Radio from '../package/radio/index.js';
import RadioGroup from '../package/radio-group/index.js';
import RadioButton from '../package/radio-button/index.js';
import Checkbox from '../package/checkbox/index.js';
import CheckboxButton from '../package/checkbox-button/index.js';
import CheckboxGroup from '../package/checkbox-group/index.js';
import Switch from '../package/switch/index.js';
import Select from '../package/select/index.js';
import Option from '../package/option/index.js';
import OptionGroup from '../package/option-group/index.js';
import Button from '../package/button/index.js';
import ButtonGroup from '../package/button-group/index.js';
import Table from '../package/table/index.js';
import TableColumn from '../package/table-column/index.js';
import DatePicker from '../package/date-picker/index.js';
import TimeSelect from '../package/time-select/index.js';
import TimePicker from '../package/time-picker/index.js';
import Popover from '../package/popover/index.js';
import Tooltip from '../package/tooltip/index.js';
import MessageBox from '../package/message-box/index.js';
import Breadcrumb from '../package/breadcrumb/index.js';
import BreadcrumbItem from '../package/breadcrumb-item/index.js';
import Form from '../package/form/index.js';
import FormItem from '../package/form-item/index.js';
import Tabs from '../package/tabs/index.js';
import TabPane from '../package/tab-pane/index.js';
import Tag from '../package/tag/index.js';
import Tree from '../package/tree/index.js';
import Notification from '../package/notification/index.js';
import Slider from '../package/slider/index.js';
import Loading from '../package/loading/index.js';
import Icon from '../package/icon/index.js';
import Row from '../package/row/index.js';
import Col from '../package/col/index.js';
import Upload from '../package/upload/index.js';
import Progress from '../package/progress/index.js';
import Spinner from '../package/spinner/index.js';
import Message from '../package/message/index.js';
import Badge from '../package/badge/index.js';
import Card from '../package/card/index.js';
import Rate from '../package/rate/index.js';
import Steps from '../package/steps/index.js';
import Step from '../package/step/index.js';
import Carousel from '../package/carousel/index.js';
import Scrollbar from '../package/scrollbar/index.js';
import CarouselItem from '../package/carousel-item/index.js';
import Collapse from '../package/collapse/index.js';
import CollapseItem from '../package/collapse-item/index.js';
import Cascader from '../package/cascader/index.js';
import ColorPicker from '../package/color-picker/index.js';
import Transfer from '../package/transfer/index.js';
import Container from '../package/container/index.js';
import Header from '../package/header/index.js';
import Aside from '../package/aside/index.js';
import Main from '../package/main/index.js';
import Footer from '../package/footer/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
	Pagination,
	Dialog,
	Autocomplete,
	Dropdown,
	DropdownMenu,
	DropdownItem,
	Menu,
	Submenu,
	MenuItem,
	MenuItemGroup,
	Input,
	InputNumber,
	Radio,
	RadioGroup,
	RadioButton,
	Checkbox,
	CheckboxButton,
	CheckboxGroup,
	Switch,
	Select,
	Option,
	OptionGroup,
	Button,
	ButtonGroup,
	Table,
	TableColumn,
	DatePicker,
	TimeSelect,
	TimePicker,
	Popover,
	Tooltip,
	Breadcrumb,
	BreadcrumbItem,
	Form,
	FormItem,
	Tabs,
	TabPane,
	Tag,
	Tree,
	Alert,
	Slider,
	Icon,
	Row,
	Col,
	Upload,
	Progress,
	Spinner,
	Badge,
	Card,
	Rate,
	Steps,
	Step,
	Carousel,
	Scrollbar,
	CarouselItem,
	Collapse,
	CollapseItem,
	Cascader,
	ColorPicker,
	Transfer,
	Container,
	Header,
	Aside,
	Main,
	Footer,
	CollapseTransition
];

const install = function (Vue, opts = {}) {
	locale.use(opts.locale);
	locale.i18n(opts.i18n);

	components.map(component => {
		Vue.component(component.name, component);
	});

	Vue.use(Loading.directive);

	Vue.prototype.$ELEMENT = {
		size: opts.size || '',
		zIndex: opts.zIndex || 2000
	};

	Vue.prototype.$loading = Loading.service;
	Vue.prototype.$msgbox = MessageBox;
	Vue.prototype.$alert = MessageBox.alert;
	Vue.prototype.$confirm = MessageBox.confirm;
	Vue.prototype.$prompt = MessageBox.prompt;
	Vue.prototype.$notify = Notification;
	Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
	install(window.Vue);
}

module.exports = {
	version: '2.4.0',
	locale: locale.use,
	i18n: locale.i18n,
	install,
	CollapseTransition,
	Loading,
	Pagination,
	Dialog,
	Autocomplete,
	Dropdown,
	DropdownMenu,
	DropdownItem,
	Menu,
	Submenu,
	MenuItem,
	MenuItemGroup,
	Input,
	InputNumber,
	Radio,
	RadioGroup,
	RadioButton,
	Checkbox,
	CheckboxButton,
	CheckboxGroup,
	Switch,
	Select,
	Option,
	OptionGroup,
	Button,
	ButtonGroup,
	Table,
	TableColumn,
	DatePicker,
	TimeSelect,
	TimePicker,
	Popover,
	Tooltip,
	MessageBox,
	Breadcrumb,
	BreadcrumbItem,
	Form,
	FormItem,
	Tabs,
	TabPane,
	Tag,
	Tree,
	Alert,
	Notification,
	Slider,
	Icon,
	Row,
	Col,
	Upload,
	Progress,
	Spinner,
	Message,
	Badge,
	Card,
	Rate,
	Steps,
	Step,
	Carousel,
	Scrollbar,
	CarouselItem,
	Collapse,
	CollapseItem,
	Cascader,
	ColorPicker,
	Transfer,
	Container,
	Header,
	Aside,
	Main,
	Footer
};

module.exports.default = module.exports;
